### ISSUE TITLE
Review and approve DIF SIG Charter template

### ISSUE THREAD

**Issue by dif-admin** [decentralized-identity/org#30]
### Proposed Template
[DIF Special Interest Group Charter Template - 20240205](https://docs.google.com/document/d/1lDFjZEzdxpvU840QReqahyQyLoeV73SyCctz7aYXkTQ/edit#heading=h.19zkkw103g5m)

### Template Source
Reverse engineered from IOT-SIG charter

### Justification
Per discussion with previous DIF leadership, the IoT-SIG template was developed as the generic SIG template.

I could not find the full context of the decision behind offering SIGs and the development of this template. However, I note that this closely follows the structure of Hyperledger SIGs, with the exception that we refer to Chair Guidelines for leadership/election/governance questions, allowing us to make these slightly briefer.

I performed some moderate editorial choices in creating this template.

### Impact
There are several SIGs missing charters, and we need to backfill them

### Followup Required
- TSC confirm this decision and/or suggest any changes in suggesting mode
- Make this available to TSC and core team to share as the SIG Charter template
- Check into org repo, in a similar manner as the WG Charter template
- Work with SIG chairs to backfill missing charters

**Comment by andorsk** [comment]
This looks good to me, but I want to note I think we should try to avoid making new SIGs when possible.

**Comment by kimdhamilton** [comment]
Fixed with #35
