### ISSUE TITLE
Review updated github repo templates and instructions

### ISSUE THREAD

**Issue by dif-admin** [decentralized-identity/org#32]
### Overview
This refreshes DIF repo templates for groups and work items, along with instructions.

### TSC To Review

- [x] Review OG repo template / instructions
    -  Repo: https://github.com/decentralized-identity/template-for-OGs
    - Tracking issue/details: https://github.com/decentralized-identity/template-for-OGs/issues/1
- [x] Review WG repo template / instructions
    - Repo: https://github.com/decentralized-identity/template-for-WGs
    - Tracking issue/details: https://github.com/decentralized-identity/template-for-WGs/issues/1
- [x] Review work items template / instructions
    - Repo: https://github.com/decentralized-identity/template-for-work-items
- [x] Review repo Work Item template / instructions. 
   - https://github.com/decentralized-identity/org/pull/40

### After Review, DIF Core Team to do:
- [x] Archive SIG template
- [x] Update documentation, including links to templates, and remove reference to SIG template
- [x] Update internal documentation for WGs. Note that adding it to the DIF web site includes this sort of thing: https://github.com/decentralized-identity/decentralized-identity.github.io/blob/master/templates/pages/working-groups/index.html

**Comment by dif-admin** [comment]
@andorsk I'm guessing moving this to "won't do" was an accident. I'm moving it back. Let me know if there's an issue

**Comment by andorsk** [comment]
Ah. Yea. We should move it back

**Comment by kimdhamilton** [comment]
This is ready for TSC review

**Comment by kimdhamilton** [comment]
To move this forward, I propose to do a walkthrough during the November TSC meeting

**Comment by kimdhamilton** [comment]
Covered in 11/27 meeting, updated instructions in README.md. TSC will review and provide feedback as appropriate

https://github.com/decentralized-identity/org/blob/main/README.md#working-at-dif
